openapi: 3.0.0

info:
  title: "Destination APP API"
  description: "API for destination app"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/api/v1"
paths: 
  /destinations/{destinationId}/comments:
    post:
      description: "Create new comment (ONLY USER)"
      tags:
        - "Comments"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
  /destinations/{destinationId}/comments/{commentId}:
    put:
      description: "update comment by id (ONLY USER)"
      tags:
        - "Comments"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    delete:
      description: "Delete comment by id (ONLY ADMIN)"
      security:
        - bearerAuth: []
      tags:
        - "Comments"
      responses:
        200:
          description: "OK"
        400:
          description: "Comment not found"
        500:
          description: "Server Error"
components:
  schemas:
    Comment:
      type: object
      properties:
        rating:
          type: number
          example: 4
        content:
          type: string
          example: "lorem ipsum"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Format of the authorization is 'Bearer JWT_Token'"

  

    

  