openapi: 3.0.0

info:
  title: "Destination APP API"
  description: "API for destination app"
  version: "1.0.0"
servers:
  - url: http://localhost:3000/api/v1
paths: 
  /favorites/{destinationId}:
    post:
      description: "Toggle favorite destination (ONLY USER)"
      parameters:
      - in: path
        required: true
        name: destinationId
        schema:
          type: integer
        description: Destination ID
      tags:
        - "Favorites"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
  /favorites:
    get:
      description: "Get User Favorites"
      tags:
        - "Favorites"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  